"""
Configuration management for FikoHouse application
Handles environment variables, defaults, and validation
"""
import os
import warnings
from functools import lru_cache
from dotenv import load_dotenv
from cryptography.fernet import Fernet

# Load .env file if it exists
load_dotenv()


class Settings:
    """Application settings loaded from environment variables"""

    # Application
    ENVIRONMENT = os.getenv("ENVIRONMENT", "development")
    DEBUG = os.getenv("DEBUG", "true").lower() == "true"

    # Database
    DATABASE_URL = os.getenv(
        "DATABASE_URL",
        "sqlite:///./fikohouse.db"
    )

    # Security
    _FERNET_KEY_RAW = os.getenv("FERNET_KEY", "").strip()
    if not _FERNET_KEY_RAW or _FERNET_KEY_RAW == "your-fernet-key-here":
        if ENVIRONMENT.lower() == "production":
            raise ValueError(
                "FERNET_KEY environment variable is not set or invalid. "
                "Generate one with: python -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\""
            )
        warnings.warn(
            "FERNET_KEY is missing/placeholder in development; using a temporary key for this process. "
            "Encrypted passwords from previous runs cannot be decrypted with this temporary key.",
            RuntimeWarning,
            stacklevel=2
        )
        FERNET_KEY = Fernet.generate_key()
    else:
        FERNET_KEY = _FERNET_KEY_RAW.encode()
        try:
            # Validate key format early. The app uses its own Fernet instance in main.py.
            Fernet(FERNET_KEY)
        except (ValueError, TypeError) as exc:
            if ENVIRONMENT.lower() == "production":
                raise ValueError(
                    "FERNET_KEY environment variable is invalid. "
                    "Expected a Fernet key generated by cryptography."
                ) from exc
            warnings.warn(
                "FERNET_KEY is invalid in development; using a temporary key for this process. "
                "Encrypted passwords from previous runs cannot be decrypted with this temporary key.",
                RuntimeWarning,
                stacklevel=2
            )
            FERNET_KEY = Fernet.generate_key()

    SECRET_KEY = os.getenv(
        "SECRET_KEY",
        ""
    )
    if not SECRET_KEY:
        raise ValueError("SECRET_KEY environment variable is required for secure session management.")

    ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "").strip()
    if not ADMIN_PASSWORD or ADMIN_PASSWORD == "your-strong-admin-password-here":
        if ENVIRONMENT.lower() == "production":
            raise ValueError(
                "ADMIN_PASSWORD environment variable is not set or invalid. "
                "Set a strong, unique admin password in your environment."
            )
        warnings.warn(
            "ADMIN_PASSWORD is missing/placeholder in development; admin login is disabled until ADMIN_PASSWORD is set.",
            RuntimeWarning,
            stacklevel=2
        )
        ADMIN_PASSWORD = None
    elif len(ADMIN_PASSWORD) < 12:
        raise ValueError("ADMIN_PASSWORD must be at least 12 characters.")

    # Server
    HOST = os.getenv("HOST", "0.0.0.0")
    PORT = int(os.getenv("PORT", "8000"))

    # CORS
    _cors_origins_raw = os.getenv("CORS_ALLOW_ORIGINS", "").strip()
    if _cors_origins_raw:
        CORS_ALLOW_ORIGINS = [origin.strip() for origin in _cors_origins_raw.split(",") if origin.strip()]
    elif ENVIRONMENT.lower() == "development":
        CORS_ALLOW_ORIGINS = ["http://localhost:8000", "http://127.0.0.1:8000"]
    else:
        CORS_ALLOW_ORIGINS = []
    if ENVIRONMENT.lower() == "production" and not CORS_ALLOW_ORIGINS:
        raise ValueError("CORS_ALLOW_ORIGINS environment variable is required in production.")

    # Feature flags
    ALLOW_SELF_SIGNED_CERTS = os.getenv("ALLOW_SELF_SIGNED_CERTS", "false").lower() == "true"

    @property
    def is_production(self) -> bool:
        """Check if running in production environment"""
        return self.ENVIRONMENT.lower() == "production"

    @property
    def is_development(self) -> bool:
        """Check if running in development environment"""
        return self.ENVIRONMENT.lower() == "development"


@lru_cache()
def get_settings() -> Settings:
    """Get application settings (cached)"""
    return Settings()


# Export settings for easy import
settings = get_settings()
